manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: diomkbs
      url-base: https://github.com/DiomKBS
  projects:
    - name: zmk
      remote: diomkbs
      revision: main
      import: app/west.yml
  self:
    path: config
